package io.github.fornewid.gradle.plugins.proguardshield.internal.r8input

import org.gradle.api.GradleException
import org.gradle.api.Task
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.FileCollection

/**
 * Reflective bridge to AGP's internal `ProguardConfigurableTask` so we can
 * snapshot the full ProGuard rule inputs *without* running R8 itself.
 *
 * R8's rule inputs are spread across several properties on AGP's task:
 * - `configurationFiles` (FileCollection) — user-authored `.pro` files + AAR
 *   consumer rules.
 * - `extractedDefaultProguardFile` (DirectoryProperty) — R8's default rule
 *   files (e.g. `proguard-android-optimize.txt`), extracted from the AGP jar.
 * - `generatedProguardFile` (FileCollection) — rules generated by AAPT2 and
 *   various AGP plugins during the build.
 *
 * [allRuleFiles] concatenates all three as a single FileCollection (the
 * DirectoryProperty is flattened via `asFileTree`). If AGP renames the class
 * or any of the methods in a future version, this helper fails with a clear
 * message so users can switch to the accurate (approach 1) task instead.
 */
internal object R8TaskInputExtractor {

    private const val BASE_CLASS = "com.android.build.gradle.internal.tasks.ProguardConfigurableTask"

    private val METHOD_NAMES = listOf(
        "getConfigurationFiles",
        "getExtractedDefaultProguardFile",
        "getGeneratedProguardFile",
    )

    fun allRuleFiles(task: Task): FileCollection {
        val baseClass = runCatching { Class.forName(BASE_CLASS) }
            .getOrElse {
                throw GradleException(
                    "ProGuard Shield fast mode: AGP internal class '$BASE_CLASS' not found. " +
                        "This AGP version is not supported by approach 2-B; " +
                        "use the standard 'proguardShield' task (approach 1) instead.",
                )
            }

        if (!baseClass.isInstance(task)) {
            throw GradleException(
                "ProGuard Shield fast mode: ${task.path} is not a ProguardConfigurableTask " +
                    "(got ${task::class.qualifiedName}). Expected AGP's R8 task.",
            )
        }

        val collections = METHOD_NAMES.map { methodName ->
            val method = runCatching { baseClass.getMethod(methodName) }
                .getOrElse {
                    throw GradleException(
                        "ProGuard Shield fast mode: method '$methodName' not found on " +
                            "$BASE_CLASS in this AGP version. Switch to the standard " +
                            "'proguardShield' task (approach 1) instead.",
                    )
                }
            val value = method.invoke(task)
            asFileCollection(value, methodName)
        }

        return collections.reduce { acc, next -> acc.plus(next) }
    }

    private fun asFileCollection(value: Any?, methodName: String): FileCollection {
        return when (value) {
            is FileCollection -> value
            is DirectoryProperty -> value.asFileTree
            else -> throw GradleException(
                "ProGuard Shield fast mode: $methodName returned an unsupported type " +
                    "(${value?.let { it::class.qualifiedName }}). Switch to the standard " +
                    "'proguardShield' task (approach 1) instead.",
            )
        }
    }
}
